import { Game } from "./game.js";

function createGame({ word, center, answers }) {
    const outers = new Set(word.replaceAll(center, '').split(''));
    answers.push(word);
    return new Game(center, [...outers], answers);
}

const data = [
    {
        word: 'triptych',
        center: 'i',
        answers: [
            [
                "chic",
                "chip",
                "chippy",
                "chirp",
                "chirpy",
                "chit",
                "chitty",
                "citric",
                "city",
                "critic",
                "cryptic",
                "hippy",
                "hitch",
                "itch",
                "itchy",
                "pitch",
                "pitchy",
                "pith",
                "pithy",
                "pity",
                "pricy",
                "pyritic",
                "pyrrhic",
                "rich",
                "thirty",
                "tippy",
                "titty",
                "trip",
                "trippy",
                "triptych",
            ]
        ],
    },
    {
        word: 'gouache',
        center: 'h',
        answers: [
                "ache",
                "achoo",
                "cache",
                "chao",
                "chug",
                "coach",
                "cooch",
                "couch",
                "cough",
                "each",
                "echo",
                "gauche",
                "gaucho",
                "gouache",
                "haha",
                "hooch",
                "huge",
                "ouch"
        ],
    },
    {
        word: 'schlomp',
        center: 'l',
        answers: [
                "clomp",
                "clomps",
                "clop",
                "cool",
                "cools",
                "loch",
                "lochs",
                "loll",
                "loom",
                "loop",
                "loos",
                "loss",
                "moloch",
                "plop",
                "poll",
                "polo",
                "pool",
                "school",
                "scollop",
                "sloop",
                "slop",
                "slosh",
                "solo",
                "spool",
        ],
    },
    {
        word: 'fritopie',
        center: 'f',
        answers: [
                "effete",
                "effort",
                "feet",
                "ferret",
                "fete",
                "fetter",
                "fief",
                "fire",
                "fireproof",
                "fitter",
                "foot",
                "footer",
                "footie",
                "fore",
                "forfeit",
                "fort",
                "forte",
                "free",
                "fret",
                "frit",
                "fritt",
                "fritter",
                "offer",
                "poof",
                "prefer",
                "proffer",
                "profit",
                "profiteer",
                "proof",
                "reef",
                "reefer",
                "refer",
                "referee",
                "referrer",
                "refit",
                "retrofit",
                "rife",
                "riff",
                "rift",
                "roof",
                "rooftop",
                "tipoff",
                "toffee",
        ],
    },
    {
        word: 'licorace',
        center: 'o',
        answers: [
                "aero",
                "aioli",
                "aloe",
                "areola",
                "cacao",
                "calico",
                "caloric",
                "calorie",
                "cello",
                "coal",
                "cocoa",
                "coerce",
                "coil",
                "coir",
                "cola",
                "collar",
                "color",
                "colorer",
                "cool",
                "cooler",
                "coral",
                "core",
                "corral",
                "creole",
                "error",
                "licorice",
                "local",
                "locale",
                "loll",
                "looie",
                "lore",
                "oilier",
                "oracle",
                "oral",
                "orca",
                "oriole",
                "recoil",
                "recolor",
                "roar",
                "rococo",
                "roil",
                "role",
                "roll",
                "roller"
        ],
    },
    {
        word: 'flippers',
        center: 'p',
        answers: [
                "ellipse",
                "ellipsis",
                "epilepsies",
                "espies",
                "flip",
                "flipper",
                "flippers",
                "flips",
                "fripperies",
                "leper",
                "lepers",
                "lips",
                "lisp",
                "peel",
                "peep",
                "peer",
                "peerless",
                "pepper",
                "peppers",
                "peppier",
                "peril",
                "perils",
                "perspire",
                "perspires",
                "pier",
                "pies",
                "pile",
                "pilfer",
                "pill",
                "pipe",
                "piper",
                "pips",
                "piss",
                "pliers",
                "plies",
                "prefer",
                "prep",
                "preppier",
                "press",
                "repel",
                "replies",
                "reprise",
                "respire",
                "ripe",
                "ripple",
                "rips",
                "seep",
                "sips",
                "sleep",
                "sleepless",
                "slip",
                "slippers",
                "spell",
                "spill",
                "spire",
                "spliff",
                "spree",
        ],
    },
    // {
    //     word: 'crosstrek',
    //     center: 'r',
    //     answers: [
    //         "stock",
    //         "rock",
    //         "took",
    //         "creek",
    //         "cook",
    //         "seek",
    //         "stocks",
    //         "socket",
    //         "seeker",
    //         "rocks",
    //         "stroke",
    //         "trek",
    //         "seeks",
    //         "socks",
    //         "rocket",
    //         "seekers",
    //         "cork"
    //     ],
    // },
    // {
    //     word: 'mineral',
    //     center: 'r',
    //     answers: [
    //         "real",
    //         "area",
    //         "learn",
    //         "near",
    //         "marine",
    //         "earlier",
    //         "remain",
    //         "rare",
    //         "manner",
    //         "miller",
    //         "rain",
    //         "linear",
    //         "rear",
    //         "earn",
    //         "airline",
    //         "inner",
    //         "rail",
    //         "alarm",
    //         "arena",
    //         "mineral",
    //         "marina",
    //         "earl",
    //         "reel",
    //         "aerial",
    //         "realm"],
    // },
    // {
    //     word: 'saltine',
    //     center: 'i',
    //     answers: [
    //         "site",
    //         "list",
    //         "line",
    //         "sites",
    //         "title",
    //         "still",
    //         "little",
    //         "lines",
    //         "lists",
    //         "titles",
    //         "listen",
    //         "satellite",
    //         "initial",
    //         "install",
    //         "saint",
    //         "essential",
    //         "assistant",
    //         "assist",
    //         "instant",
    //         "nine",
    //         "tennis",
    //         "stainless",
    //         "till",
    //         "lies",
    //         "silent",
    //         "elite",
    //         "illness",
    //         "titans",
    //         "intent",
    //         "entities",
    //         "ties",
    //         "tail",
    //         "alien",
    //         "essentials",
    //         "isle",
    //         "nail",
    //         "inns",
    //         "tile",
    //         "inline",
    //         "intense",
    //         "alias",
    //         "saints",
    //         "satin",
    //         "nails",
    //         "assists",
    //         "tiles",
    //         "sail"
    //     ],
    // },
]

export const games = data.map(createGame);